apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "9090"
spec:
  externalUrl: http://monitoring.my.systems:8081
  resources:
    requests:
      memory: 400Mi
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "9090"
spec:
  replicas: 3
  externalUrl: http://monitoring.my.systems:8081
  resources:
    requests:
      memory: 400Mi